### ISSUE TITLE
Ajouter le topic «remarkable-tablet» Adding the “remarkable-tablet” topic

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [jacob414/rm-seyes#1]
Comme décris ici : https://remarkable.guide/devel/github.html
Il serait judicieux, pour question d'exposition, d'utiliser le topic «[remarkable-tablet](https://github.com/topics/remarkable-tablet)» pour permettre de plus facilement, faire découvrir votre repo, y compris pour les francophones intéressés par celle-ci. Je vous ai découvert via le reddit [r/RemarkableTablet](https://www.reddit.com/r/RemarkableTablet/), heureusement, surtout que je le consulte occasionnellement et je ne possède pas de compte Reddit.

As described here : https://remarkable.guide/devel/github.html
It would be preferable, as a way to showcase your repo, to use the “[remarkable-tablet](https://github.com/topics/remarkable-tablet)” topic, to allow for easier discovery of it, for other french-speaking users notably. I've discovered your repo via Subreddit [r/RemarkableTablet](https://www.reddit.com/r/RemarkableTablet/), thankfully, as I don't consult it often, and don't have any Reddit account.

**Comment by jacob414** [comment]
Bien sûr, bonne idée
